# Generated by Django 5.0.2 on 2024-02-11 05:42

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("member_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="member",
            name="member_id",
            field=models.UUIDField(
                default=uuid.uuid4, primary_key=True, serialize=False
            ),
        ),
    ]
