# Generated by Django 5.0.2 on 2024-02-15 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("member_app", "0003_member_account_number_member_address_1_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="member",
            name="nrc",
            field=models.CharField(max_length=11),
        ),
    ]
