# Generated by Django 5.0.2 on 2024-02-15 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("member_app", "0004_alter_member_nrc"),
    ]

    operations = [
        migrations.AlterField(
            model_name="member",
            name="account_number",
            field=models.CharField(max_length=20, verbose_name="Account Number"),
        ),
        migrations.AlterField(
            model_name="member",
            name="address_1",
            field=models.CharField(max_length=50, verbose_name="Address 1"),
        ),
        migrations.AlterField(
            model_name="member",
            name="bank_name",
            field=models.CharField(max_length=50, verbose_name="Bank name"),
        ),
        migrations.AlterField(
            model_name="member",
            name="branch_address",
            field=models.CharField(max_length=20, verbose_name="Branch address"),
        ),
        migrations.AlterField(
            model_name="member",
            name="branch_code",
            field=models.CharField(max_length=3, verbose_name="Branch code"),
        ),
        migrations.AlterField(
            model_name="member",
            name="branch_name",
            field=models.CharField(max_length=50, verbose_name="Branch name"),
        ),
        migrations.AlterField(
            model_name="member",
            name="country",
            field=models.CharField(max_length=20, verbose_name="Country"),
        ),
        migrations.AlterField(
            model_name="member",
            name="member_mobile",
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name="member",
            name="next_of_kin_fullname",
            field=models.CharField(
                max_length=30, verbose_name="Next of Kin (Fullname)"
            ),
        ),
        migrations.AlterField(
            model_name="member",
            name="next_of_kin_mobile",
            field=models.CharField(max_length=12, verbose_name="Next of kin mobile"),
        ),
        migrations.AlterField(
            model_name="member",
            name="province",
            field=models.CharField(max_length=20, verbose_name="Province/State"),
        ),
        migrations.AlterField(
            model_name="member",
            name="town",
            field=models.CharField(max_length=20, verbose_name="Town"),
        ),
    ]
