# Generated by Django 5.0.2 on 2024-02-15 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "member_app",
            "0005_alter_member_account_number_alter_member_address_1_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="member",
            name="next_of_kin_nrc",
            field=models.CharField(
                default="11111111", max_length=11, verbose_name="Next of Kin (NRC)"
            ),
        ),
    ]
