# Generated by Django 5.0.2 on 2024-02-15 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("member_app", "0006_member_next_of_kin_nrc"),
    ]

    operations = [
        migrations.AlterField(
            model_name="member",
            name="next_of_kin_nrc",
            field=models.CharField(max_length=11, verbose_name="Next of Kin (NRC)"),
        ),
    ]
