# Generated by Django 5.0.2 on 2024-02-11 01:40

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("account_app", "0001_initial"),
        ("member_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Declaration",
            fields=[
                (
                    "declaration_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Globally Unique Identifier",
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "declaration_date",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="The date and time declaration made.",
                    ),
                ),
                (
                    "member_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="member_app.member",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "transaction_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "transaction_date",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Date payment made against the declaration",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Total Amount of declared amount",
                        max_digits=10,
                    ),
                ),
                (
                    "declaration",
                    models.ForeignKey(
                        help_text="FK Declaration ID",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="declaration_app.declaration",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TransactionType",
            fields=[
                (
                    "transaction_type_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        help_text="FK Transaction Type ID",
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("description", models.CharField(max_length=150)),
                (
                    "account",
                    models.ForeignKey(
                        help_text="FK Account_ID affected by this transaction",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="account_app.account",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TransactionTypeDeclaration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Amount for the transaction",
                        max_digits=10,
                    ),
                ),
                (
                    "declaration",
                    models.ForeignKey(
                        help_text="FK Declaration ID",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="declaration_app.declaration",
                    ),
                ),
                (
                    "transaction_type",
                    models.ForeignKey(
                        help_text="FK transaction_type_id track",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="declaration_app.transactiontype",
                    ),
                ),
            ],
        ),
    ]
